version: "3.8"
services:
  autoshow:
    build:
      context: './'
      dockerfile: Dockerfile
    container_name: autoshow_docker_compose
    ports: # array of ports
      - 3000:3000
      - 3001:3000  
    volumes:
      - './:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true